[package]
name = "pepeeltoro41/jecs-utils"
version = "1.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["node_modules", "src/index.d.ts", "package.json", "jecs.luau"]

[dependencies]
jecs = "ukendio/jecs@0.9.0"
